<!DOCTYPE html>
<html>
% include('head.tpl', title="Home")
<body>
% include('header.tpl')
<div class="container">
    <h1>Anisopter</h1>
    <h2>Motivation</h2>
    <p>
        Dragonflies are insects of the order Odonata, suborder Anisoptera
        \cite{dfwiki}. They are notoriously effective at prey capture, with
        success rates ranging from 76\% to 97\% \cite{Olberg2011}, making the
        neural processes that underlie this ability particularly interesting to
        investigate. There has been substantial research into the visual system
        of dragonflies \cite{Wiederman2008, w13}, but what seems to be lacking
        is an effective tool that links models of the various mechanisms
        involved in this process together, which could help us better understand
        the particular function of each layer within the system.
    </p>
    <p>
        At the core of this apparatus, the centrifugal small target motion
        detector one neuron (CSTMD1) is a higher order visual neuron in the
        brain of the dragonfly that reacts to the presentation of multiple
        visual stimuli by firing as if only one of the stimuli were present.
        This is presumably an attentional selection mechanism \cite{w13}. At
        Professor Murray Shanahan's lab, researchers have simulated the large
        contralateral dendritic field of the CSTMD1 neuron with a biophysical
        multi-compartmental Hodgkin-Huxley model. Along with Klaus Stiefel
        \cite{ne13}, they found that with certain numbers of inhibitory synapses
        and potassium conductance densities, two mutually-coupled CSTMD1 neurons
        are capable of a bistable switching process between two input patterns.
        In order to confirm that this neuron is indeed responsible for target
        selection, it would be useful to be able to model the CSTMD1 as a part
        of a whole visual system.
    </p>
    <h2>Goals</h2>
    <ul>
        <li>
            Provide a connected model of dragonfly target selection, starting
            from the visual input to the retina and ending with the motion of
            the dragonfly.
        </li>
        <li>
            Provide a graphical interface for each module and for the system
            as a whole, allowing users to run simulations and view useful
            information on the processing done by each layer.
        </li>
        <li>
            Provide persistent, easily accessible storage of experimental data
            generated by the individual layers and the system as a whole.
        </li>
        <li>
            Provide a platform for potentially replicating the behaviour of a
            real dragonfly during prey capture.
        </li>
    </ul>
    <h2>How it works</h2>
    <div class="row">
         <div class="col-md-12">
             <img src="/assets/images/how_it_works.png"
                  class="img-responsive" alt="How It Works" />
         </div>
    </div>
    <h3>Target Animation</h3>
    <h3>ESTMD</h3>
    <h3>CSTMD1</h3>
    <h3>Pattern Recognition</h3>
    <h3>Action Selection</h3>
</div>
% include('footer.tpl')
</body>
</html>